/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ThirdpartyRouteImport } from './routes/thirdparty'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UtilitiesWaterRouteImport } from './routes/utilities.water'
import { Route as UtilitiesGasRouteImport } from './routes/utilities.gas'
import { Route as ResidentVisitorsRouteImport } from './routes/resident.visitors'
import { Route as ResidentProfileRouteImport } from './routes/resident.profile'
import { Route as ResidentPaymentsRouteImport } from './routes/resident.payments'
import { Route as ResidentNoticesRouteImport } from './routes/resident.notices'
import { Route as ResidentDocumentsRouteImport } from './routes/resident.documents'
import { Route as ResidentComplaintsRouteImport } from './routes/resident.complaints'
import { Route as ResidentBillsRouteImport } from './routes/resident.bills'
import { Route as ResidentApartmentRouteImport } from './routes/resident.apartment'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminVacantListRouteImport } from './routes/admin.vacant-list'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentRequestsRouteImport } from './routes/admin.payment-requests'
import { Route as AdminParkingRouteImport } from './routes/admin.parking'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomeContentRouteImport } from './routes/admin.home-content'
import { Route as AdminHiddenToolsRouteImport } from './routes/admin.hidden-tools'
import { Route as AdminFinancialLedgerRouteImport } from './routes/admin.financial-ledger'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminDailyRentRouteImport } from './routes/admin.daily-rent'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminBulkUtilityRouteImport } from './routes/admin.bulk-utility'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAssetsInventoryRouteImport } from './routes/admin.assets-inventory'
import { Route as AdminApartmentsRouteImport } from './routes/admin.apartments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAccessControlRouteImport } from './routes/admin.access-control'
import { Route as ApiPublicAutoBackupRouteImport } from './routes/api/public/auto-backup'
import { Route as AdminLedgerTypeIdRouteImport } from './routes/admin.ledger.$type.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ThirdpartyRoute = ThirdpartyRouteImport.update({
  id: '/thirdparty',
  path: '/thirdparty',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UtilitiesWaterRoute = UtilitiesWaterRouteImport.update({
  id: '/utilities/water',
  path: '/utilities/water',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesGasRoute = UtilitiesGasRouteImport.update({
  id: '/utilities/gas',
  path: '/utilities/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentVisitorsRoute = ResidentVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentProfileRoute = ResidentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentPaymentsRoute = ResidentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentNoticesRoute = ResidentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentDocumentsRoute = ResidentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentComplaintsRoute = ResidentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentBillsRoute = ResidentBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentApartmentRoute = ResidentApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVacantListRoute = AdminVacantListRouteImport.update({
  id: '/vacant-list',
  path: '/vacant-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentRequestsRoute = AdminPaymentRequestsRouteImport.update({
  id: '/payment-requests',
  path: '/payment-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParkingRoute = AdminParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeContentRoute = AdminHomeContentRouteImport.update({
  id: '/home-content',
  path: '/home-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHiddenToolsRoute = AdminHiddenToolsRouteImport.update({
  id: '/hidden-tools',
  path: '/hidden-tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialLedgerRoute = AdminFinancialLedgerRouteImport.update({
  id: '/financial-ledger',
  path: '/financial-ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyRentRoute = AdminDailyRentRouteImport.update({
  id: '/daily-rent',
  path: '/daily-rent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkUtilityRoute = AdminBulkUtilityRouteImport.update({
  id: '/bulk-utility',
  path: '/bulk-utility',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsInventoryRoute = AdminAssetsInventoryRouteImport.update({
  id: '/assets-inventory',
  path: '/assets-inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApartmentsRoute = AdminApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessControlRoute = AdminAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicAutoBackupRoute = ApiPublicAutoBackupRouteImport.update({
  id: '/api/public/auto-backup',
  path: '/api/public/auto-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLedgerTypeIdRoute = AdminLedgerTypeIdRouteImport.update({
  id: '/ledger/$type/$id',
  path: '/ledger/$type/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/resident': typeof ResidentRouteWithChildren
  '/thirdparty': typeof ThirdpartyRoute
  '/welcome': typeof WelcomeRoute
  '/admin/access-control': typeof AdminAccessControlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/assets-inventory': typeof AdminAssetsInventoryRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bulk-utility': typeof AdminBulkUtilityRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/daily-rent': typeof AdminDailyRentRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/financial-ledger': typeof AdminFinancialLedgerRoute
  '/admin/hidden-tools': typeof AdminHiddenToolsRoute
  '/admin/home-content': typeof AdminHomeContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/vacant-list': typeof AdminVacantListRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/apartment': typeof ResidentApartmentRoute
  '/resident/bills': typeof ResidentBillsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/documents': typeof ResidentDocumentsRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/utilities/gas': typeof UtilitiesGasRoute
  '/utilities/water': typeof UtilitiesWaterRoute
  '/admin/': typeof AdminIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/api/public/auto-backup': typeof ApiPublicAutoBackupRoute
  '/admin/ledger/$type/$id': typeof AdminLedgerTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/thirdparty': typeof ThirdpartyRoute
  '/welcome': typeof WelcomeRoute
  '/admin/access-control': typeof AdminAccessControlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/assets-inventory': typeof AdminAssetsInventoryRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bulk-utility': typeof AdminBulkUtilityRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/daily-rent': typeof AdminDailyRentRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/financial-ledger': typeof AdminFinancialLedgerRoute
  '/admin/hidden-tools': typeof AdminHiddenToolsRoute
  '/admin/home-content': typeof AdminHomeContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/vacant-list': typeof AdminVacantListRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/apartment': typeof ResidentApartmentRoute
  '/resident/bills': typeof ResidentBillsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/documents': typeof ResidentDocumentsRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/utilities/gas': typeof UtilitiesGasRoute
  '/utilities/water': typeof UtilitiesWaterRoute
  '/admin': typeof AdminIndexRoute
  '/resident': typeof ResidentIndexRoute
  '/api/public/auto-backup': typeof ApiPublicAutoBackupRoute
  '/admin/ledger/$type/$id': typeof AdminLedgerTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/amenities': typeof AmenitiesRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/resident': typeof ResidentRouteWithChildren
  '/thirdparty': typeof ThirdpartyRoute
  '/welcome': typeof WelcomeRoute
  '/admin/access-control': typeof AdminAccessControlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/assets-inventory': typeof AdminAssetsInventoryRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bulk-utility': typeof AdminBulkUtilityRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/daily-rent': typeof AdminDailyRentRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/financial-ledger': typeof AdminFinancialLedgerRoute
  '/admin/hidden-tools': typeof AdminHiddenToolsRoute
  '/admin/home-content': typeof AdminHomeContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/vacant-list': typeof AdminVacantListRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/apartment': typeof ResidentApartmentRoute
  '/resident/bills': typeof ResidentBillsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/documents': typeof ResidentDocumentsRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/utilities/gas': typeof UtilitiesGasRoute
  '/utilities/water': typeof UtilitiesWaterRoute
  '/admin/': typeof AdminIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/api/public/auto-backup': typeof ApiPublicAutoBackupRoute
  '/admin/ledger/$type/$id': typeof AdminLedgerTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/contact'
    | '/demo'
    | '/gallery'
    | '/location'
    | '/login'
    | '/pending-approval'
    | '/resident'
    | '/thirdparty'
    | '/welcome'
    | '/admin/access-control'
    | '/admin/announcements'
    | '/admin/apartments'
    | '/admin/assets-inventory'
    | '/admin/backup'
    | '/admin/bulk-utility'
    | '/admin/complaints'
    | '/admin/credentials'
    | '/admin/daily-rent'
    | '/admin/directory'
    | '/admin/documents'
    | '/admin/financial-ledger'
    | '/admin/hidden-tools'
    | '/admin/home-content'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parking'
    | '/admin/payment-requests'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tenants'
    | '/admin/vacant-list'
    | '/admin/visitors'
    | '/resident/apartment'
    | '/resident/bills'
    | '/resident/complaints'
    | '/resident/documents'
    | '/resident/notices'
    | '/resident/payments'
    | '/resident/profile'
    | '/resident/visitors'
    | '/utilities/gas'
    | '/utilities/water'
    | '/admin/'
    | '/resident/'
    | '/api/public/auto-backup'
    | '/admin/ledger/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/contact'
    | '/demo'
    | '/gallery'
    | '/location'
    | '/login'
    | '/pending-approval'
    | '/thirdparty'
    | '/welcome'
    | '/admin/access-control'
    | '/admin/announcements'
    | '/admin/apartments'
    | '/admin/assets-inventory'
    | '/admin/backup'
    | '/admin/bulk-utility'
    | '/admin/complaints'
    | '/admin/credentials'
    | '/admin/daily-rent'
    | '/admin/directory'
    | '/admin/documents'
    | '/admin/financial-ledger'
    | '/admin/hidden-tools'
    | '/admin/home-content'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parking'
    | '/admin/payment-requests'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tenants'
    | '/admin/vacant-list'
    | '/admin/visitors'
    | '/resident/apartment'
    | '/resident/bills'
    | '/resident/complaints'
    | '/resident/documents'
    | '/resident/notices'
    | '/resident/payments'
    | '/resident/profile'
    | '/resident/visitors'
    | '/utilities/gas'
    | '/utilities/water'
    | '/admin'
    | '/resident'
    | '/api/public/auto-backup'
    | '/admin/ledger/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/amenities'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/contact'
    | '/demo'
    | '/gallery'
    | '/location'
    | '/login'
    | '/pending-approval'
    | '/resident'
    | '/thirdparty'
    | '/welcome'
    | '/admin/access-control'
    | '/admin/announcements'
    | '/admin/apartments'
    | '/admin/assets-inventory'
    | '/admin/backup'
    | '/admin/bulk-utility'
    | '/admin/complaints'
    | '/admin/credentials'
    | '/admin/daily-rent'
    | '/admin/directory'
    | '/admin/documents'
    | '/admin/financial-ledger'
    | '/admin/hidden-tools'
    | '/admin/home-content'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/parking'
    | '/admin/payment-requests'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tenants'
    | '/admin/vacant-list'
    | '/admin/visitors'
    | '/resident/apartment'
    | '/resident/bills'
    | '/resident/complaints'
    | '/resident/documents'
    | '/resident/notices'
    | '/resident/payments'
    | '/resident/profile'
    | '/resident/visitors'
    | '/utilities/gas'
    | '/utilities/water'
    | '/admin/'
    | '/resident/'
    | '/api/public/auto-backup'
    | '/admin/ledger/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AmenitiesRoute: typeof AmenitiesRoute
  ApartmentsRoute: typeof ApartmentsRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ResidentRoute: typeof ResidentRouteWithChildren
  ThirdpartyRoute: typeof ThirdpartyRoute
  WelcomeRoute: typeof WelcomeRoute
  UtilitiesGasRoute: typeof UtilitiesGasRoute
  UtilitiesWaterRoute: typeof UtilitiesWaterRoute
  ApiPublicAutoBackupRoute: typeof ApiPublicAutoBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thirdparty': {
      id: '/thirdparty'
      path: '/thirdparty'
      fullPath: '/thirdparty'
      preLoaderRoute: typeof ThirdpartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/': {
      id: '/resident/'
      path: '/'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/utilities/water': {
      id: '/utilities/water'
      path: '/utilities/water'
      fullPath: '/utilities/water'
      preLoaderRoute: typeof UtilitiesWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/gas': {
      id: '/utilities/gas'
      path: '/utilities/gas'
      fullPath: '/utilities/gas'
      preLoaderRoute: typeof UtilitiesGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/visitors': {
      id: '/resident/visitors'
      path: '/visitors'
      fullPath: '/resident/visitors'
      preLoaderRoute: typeof ResidentVisitorsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/profile': {
      id: '/resident/profile'
      path: '/profile'
      fullPath: '/resident/profile'
      preLoaderRoute: typeof ResidentProfileRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/payments': {
      id: '/resident/payments'
      path: '/payments'
      fullPath: '/resident/payments'
      preLoaderRoute: typeof ResidentPaymentsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/notices': {
      id: '/resident/notices'
      path: '/notices'
      fullPath: '/resident/notices'
      preLoaderRoute: typeof ResidentNoticesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/documents': {
      id: '/resident/documents'
      path: '/documents'
      fullPath: '/resident/documents'
      preLoaderRoute: typeof ResidentDocumentsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/complaints': {
      id: '/resident/complaints'
      path: '/complaints'
      fullPath: '/resident/complaints'
      preLoaderRoute: typeof ResidentComplaintsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/bills': {
      id: '/resident/bills'
      path: '/bills'
      fullPath: '/resident/bills'
      preLoaderRoute: typeof ResidentBillsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/apartment': {
      id: '/resident/apartment'
      path: '/apartment'
      fullPath: '/resident/apartment'
      preLoaderRoute: typeof ResidentApartmentRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vacant-list': {
      id: '/admin/vacant-list'
      path: '/vacant-list'
      fullPath: '/admin/vacant-list'
      preLoaderRoute: typeof AdminVacantListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-requests': {
      id: '/admin/payment-requests'
      path: '/payment-requests'
      fullPath: '/admin/payment-requests'
      preLoaderRoute: typeof AdminPaymentRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parking': {
      id: '/admin/parking'
      path: '/parking'
      fullPath: '/admin/parking'
      preLoaderRoute: typeof AdminParkingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-content': {
      id: '/admin/home-content'
      path: '/home-content'
      fullPath: '/admin/home-content'
      preLoaderRoute: typeof AdminHomeContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hidden-tools': {
      id: '/admin/hidden-tools'
      path: '/hidden-tools'
      fullPath: '/admin/hidden-tools'
      preLoaderRoute: typeof AdminHiddenToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial-ledger': {
      id: '/admin/financial-ledger'
      path: '/financial-ledger'
      fullPath: '/admin/financial-ledger'
      preLoaderRoute: typeof AdminFinancialLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-rent': {
      id: '/admin/daily-rent'
      path: '/daily-rent'
      fullPath: '/admin/daily-rent'
      preLoaderRoute: typeof AdminDailyRentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-utility': {
      id: '/admin/bulk-utility'
      path: '/bulk-utility'
      fullPath: '/admin/bulk-utility'
      preLoaderRoute: typeof AdminBulkUtilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets-inventory': {
      id: '/admin/assets-inventory'
      path: '/assets-inventory'
      fullPath: '/admin/assets-inventory'
      preLoaderRoute: typeof AdminAssetsInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apartments': {
      id: '/admin/apartments'
      path: '/apartments'
      fullPath: '/admin/apartments'
      preLoaderRoute: typeof AdminApartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-control': {
      id: '/admin/access-control'
      path: '/access-control'
      fullPath: '/admin/access-control'
      preLoaderRoute: typeof AdminAccessControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/auto-backup': {
      id: '/api/public/auto-backup'
      path: '/api/public/auto-backup'
      fullPath: '/api/public/auto-backup'
      preLoaderRoute: typeof ApiPublicAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ledger/$type/$id': {
      id: '/admin/ledger/$type/$id'
      path: '/ledger/$type/$id'
      fullPath: '/admin/ledger/$type/$id'
      preLoaderRoute: typeof AdminLedgerTypeIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessControlRoute: typeof AdminAccessControlRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApartmentsRoute: typeof AdminApartmentsRoute
  AdminAssetsInventoryRoute: typeof AdminAssetsInventoryRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminBulkUtilityRoute: typeof AdminBulkUtilityRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminDailyRentRoute: typeof AdminDailyRentRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFinancialLedgerRoute: typeof AdminFinancialLedgerRoute
  AdminHiddenToolsRoute: typeof AdminHiddenToolsRoute
  AdminHomeContentRoute: typeof AdminHomeContentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParkingRoute: typeof AdminParkingRoute
  AdminPaymentRequestsRoute: typeof AdminPaymentRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminVacantListRoute: typeof AdminVacantListRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLedgerTypeIdRoute: typeof AdminLedgerTypeIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessControlRoute: AdminAccessControlRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApartmentsRoute: AdminApartmentsRoute,
  AdminAssetsInventoryRoute: AdminAssetsInventoryRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminBulkUtilityRoute: AdminBulkUtilityRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminDailyRentRoute: AdminDailyRentRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFinancialLedgerRoute: AdminFinancialLedgerRoute,
  AdminHiddenToolsRoute: AdminHiddenToolsRoute,
  AdminHomeContentRoute: AdminHomeContentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParkingRoute: AdminParkingRoute,
  AdminPaymentRequestsRoute: AdminPaymentRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminVacantListRoute: AdminVacantListRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLedgerTypeIdRoute: AdminLedgerTypeIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResidentRouteChildren {
  ResidentApartmentRoute: typeof ResidentApartmentRoute
  ResidentBillsRoute: typeof ResidentBillsRoute
  ResidentComplaintsRoute: typeof ResidentComplaintsRoute
  ResidentDocumentsRoute: typeof ResidentDocumentsRoute
  ResidentNoticesRoute: typeof ResidentNoticesRoute
  ResidentPaymentsRoute: typeof ResidentPaymentsRoute
  ResidentProfileRoute: typeof ResidentProfileRoute
  ResidentVisitorsRoute: typeof ResidentVisitorsRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentApartmentRoute: ResidentApartmentRoute,
  ResidentBillsRoute: ResidentBillsRoute,
  ResidentComplaintsRoute: ResidentComplaintsRoute,
  ResidentDocumentsRoute: ResidentDocumentsRoute,
  ResidentNoticesRoute: ResidentNoticesRoute,
  ResidentPaymentsRoute: ResidentPaymentsRoute,
  ResidentProfileRoute: ResidentProfileRoute,
  ResidentVisitorsRoute: ResidentVisitorsRoute,
  ResidentIndexRoute: ResidentIndexRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AmenitiesRoute: AmenitiesRoute,
  ApartmentsRoute: ApartmentsRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ResidentRoute: ResidentRouteWithChildren,
  ThirdpartyRoute: ThirdpartyRoute,
  WelcomeRoute: WelcomeRoute,
  UtilitiesGasRoute: UtilitiesGasRoute,
  UtilitiesWaterRoute: UtilitiesWaterRoute,
  ApiPublicAutoBackupRoute: ApiPublicAutoBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
