-- Create tower_announcements table
CREATE TABLE IF NOT EXISTS tower_announcements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL,
    message     TEXT NOT NULL,
    posted_by   TEXT DEFAULT 'System Admin',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE tower_announcements ENABLE ROW LEVEL SECURITY;

-- Allow read access for everyone (anonymous & authenticated)
CREATE POLICY "Allow read access for everyone" ON tower_announcements
    FOR SELECT USING (true);

-- Allow authenticated users (Admins/Staff) to insert
CREATE POLICY "Allow insert for authenticated users only" ON tower_announcements
    FOR INSERT TO authenticated WITH CHECK (true);

-- Allow authenticated users to update their own records
CREATE POLICY "Allow update for authenticated users only" ON tower_announcements
    FOR UPDATE TO authenticated USING (true);

-- Allow authenticated users to delete records
CREATE POLICY "Allow delete for authenticated users only" ON tower_announcements
    FOR DELETE TO authenticated USING (true);
